In [3]:
#Tensörler
import numpy as np

In [4]:
T1 = np.array([
    [[1,2,3], [4,5,6], [7,8,9]],
    [[10,20,30], [40,50,60], [70,80,90]],
    [[100,200,300], [400,500,600], [700,800,900]],
    ])
T1

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 10,  20,  30],
        [ 40,  50,  60],
        [ 70,  80,  90]],

       [[100, 200, 300],
        [400, 500, 600],
        [700, 800, 900]]])

In [5]:
T2 = np.array([
    [[0,0,0], [0,0,0], [0,0,0]],
    [[1,1,1], [1,1,1], [1,1,1]],
    [[2,2,2], [2,2,2], [2,2,2]]
])

T2

array([[[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[2, 2, 2],
        [2, 2, 2],
        [2, 2, 2]]])

In [6]:
A = T1 + T2
A

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [7]:
np.add(T1, T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[ 11,  21,  31],
        [ 41,  51,  61],
        [ 71,  81,  91]],

       [[102, 202, 302],
        [402, 502, 602],
        [702, 802, 902]]])

In [8]:
S = T1 - T2
S

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [9]:
np.subtract(T1,T2)

array([[[  1,   2,   3],
        [  4,   5,   6],
        [  7,   8,   9]],

       [[  9,  19,  29],
        [ 39,  49,  59],
        [ 69,  79,  89]],

       [[ 98, 198, 298],
        [398, 498, 598],
        [698, 798, 898]]])

In [10]:
P = T1*T2
P

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [11]:
np.multiply(T1, T2)

array([[[   0,    0,    0],
        [   0,    0,    0],
        [   0,    0,    0]],

       [[  10,   20,   30],
        [  40,   50,   60],
        [  70,   80,   90]],

       [[ 200,  400,  600],
        [ 800, 1000, 1200],
        [1400, 1600, 1800]]])

In [13]:
import warnings
warnings.filterwarnings('ignore')

In [14]:
D = T1/T2
D

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [15]:
np.divide(T1, T2)

array([[[ inf,  inf,  inf],
        [ inf,  inf,  inf],
        [ inf,  inf,  inf]],

       [[ 10.,  20.,  30.],
        [ 40.,  50.,  60.],
        [ 70.,  80.,  90.]],

       [[ 50., 100., 150.],
        [200., 250., 300.],
        [350., 400., 450.]]])

In [16]:
#Denklem Çözümü (Ax = B)

In [17]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
B = np.random.random((3,1))
B

array([[0.54505968],
       [0.87345569],
       [0.79125479]])

In [19]:
X = np.dot(np.linalg.inv(A), B)
X

array([[-1.29441487e+15],
       [ 2.58882974e+15],
       [-1.29441487e+15]])

In [20]:
X = np.matmul(np.linalg.inv(A), B)
X

array([[-1.29441487e+15],
       [ 2.58882974e+15],
       [-1.29441487e+15]])

In [22]:
X = np.linalg.inv(A)@B
X

array([[-1.29441487e+15],
       [ 2.58882974e+15],
       [-1.29441487e+15]])

In [23]:
X = np.linalg.solve(A, B)
X

array([[-1.29441487e+15],
       [ 2.58882974e+15],
       [-1.29441487e+15]])

In [24]:
#PANDAS

In [1]:
import numpy as np
import pandas as pd
import math
import warnings
warnings.filterwarnings('ignore')

In [26]:
#Seriler

In [27]:
v = np.array([1,2,3,4,5,6,7])
s1 = pd.Series(v)
s1

0    1
1    2
2    3
3    4
4    5
5    6
6    7
dtype: int32

In [28]:
s1.dtype

dtype('int32')

In [33]:
print(s1.values.itemsize)

4


In [35]:
s1.nbytes

28

In [36]:
#shape, ndim, len(s1), count(), size

In [37]:
s0 = pd.Series([1,2,3], index = ['a', 'b', 'c'])
s0

a    1
b    2
c    3
dtype: int64

In [38]:
s1.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g']
s1

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int32

In [39]:
v2 = np.random.random(10)
ind2 = np.arange(0, 10)
s = pd.Series(v2, ind2)
v2, ind2, s

(array([0.53109719, 0.77255982, 0.86570191, 0.9963328 , 0.26030216,
        0.17682443, 0.24984579, 0.72811124, 0.15133121, 0.1993614 ]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 0    0.531097
 1    0.772560
 2    0.865702
 3    0.996333
 4    0.260302
 5    0.176824
 6    0.249846
 7    0.728111
 8    0.151331
 9    0.199361
 dtype: float64)

In [40]:
s.dtype

dtype('float64')

In [41]:
s.values.itemsize

8

In [42]:
s.nbytes

80

In [43]:
dict1 = {'a1' : 10, 'a2' : 20, 'a3' : 30, 'a4' : 40}
s3 = pd.Series(dict1)
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [44]:
pd.Series(99, index = [0, 1, 2, 3, 4, 5])

0    99
1    99
2    99
3    99
4    99
5    99
dtype: int64

In [45]:
#Serileri Bölme (Slicing)

In [46]:
s

0    0.531097
1    0.772560
2    0.865702
3    0.996333
4    0.260302
5    0.176824
6    0.249846
7    0.728111
8    0.151331
9    0.199361
dtype: float64

In [47]:
s[:]

0    0.531097
1    0.772560
2    0.865702
3    0.996333
4    0.260302
5    0.176824
6    0.249846
7    0.728111
8    0.151331
9    0.199361
dtype: float64

In [48]:
s[0:3]

0    0.531097
1    0.772560
2    0.865702
dtype: float64

In [49]:
s[-1:]

9    0.199361
dtype: float64

In [50]:
s[:4]

0    0.531097
1    0.772560
2    0.865702
3    0.996333
dtype: float64

In [51]:
s[:-2]

0    0.531097
1    0.772560
2    0.865702
3    0.996333
4    0.260302
5    0.176824
6    0.249846
7    0.728111
dtype: float64

In [52]:
s[-3:-1]

7    0.728111
8    0.151331
dtype: float64

In [53]:
#Serileri Birleştirme (Append)

In [54]:
s2 = s1.copy()

In [55]:
s3

a1    10
a2    20
a3    30
a4    40
dtype: int64

In [57]:
s4 = s2.append(s3)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [58]:
s4.drop('a4', inplace = False)

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [59]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4    40
dtype: int64

In [60]:
s4.drop('a4', inplace = True)
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [61]:
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
dtype: int64

In [62]:
s4 = s4.append(pd.Series({'a4' : 7}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a3    30
a4     7
dtype: int64

In [63]:
s4 = s4.drop('a3')
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a4     7
dtype: int64

In [65]:
s4 = s4.append(pd.Series({'a3' : 77}))
s4

a      1
b      2
c      3
d      4
e      5
f      6
g      7
a1    10
a2    20
a4     7
a3    77
dtype: int64

In [66]:
s3

a1    10
a2    20
a3    30
a4    40
a3    77
dtype: int64

In [67]:
s3.drop('a3', inplace = True)

In [68]:
s3

a1    10
a2    20
a4    40
dtype: int64

In [70]:
s3 = s3.append(pd.Series({'a3' : 30}))
s3

a1    10
a2    20
a4    40
a3    30
dtype: int64

In [73]:
#Seriler üzerindeki operasyonlar

In [74]:
v1 = np.array([10,20,30])
v2 = np.array([1,2,3])
s1 = pd.Series(v1)
s2 = pd.Series(v2)
s1, s2

(0    10
 1    20
 2    30
 dtype: int32,
 0    1
 1    2
 2    3
 dtype: int32)

In [75]:
s1.add(s2)

0    11
1    22
2    33
dtype: int32

In [76]:
s1.sub(s2)

0     9
1    18
2    27
dtype: int32

In [77]:
s1.subtract(s2)

0     9
1    18
2    27
dtype: int32

In [78]:
s1.add(9)

0    19
1    29
2    39
dtype: int32

In [79]:
s1.mul(s2)

0    10
1    40
2    90
dtype: int32

In [80]:
s1.multiply(s2)

0    10
1    40
2    90
dtype: int32

In [81]:
s1.multiply(1000)

0    10000
1    20000
2    30000
dtype: int32

In [82]:
s1.divide(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [83]:
s1.div(s2)

0    10.0
1    10.0
2    10.0
dtype: float64

In [84]:
#max(), min(), mean(), median(), std()

In [85]:
s1.equals(s2)

False

In [86]:
s4 = s1

In [87]:
s1.equals(s4)

True

In [88]:
s5 = pd.Series([1,1,2,2,3,3], index = [0,1,2,3,4,5])
s5

0    1
1    1
2    2
3    2
4    3
5    3
dtype: int64

In [89]:
s5.value_counts()

1    2
2    2
3    2
dtype: int64

In [90]:
#DataFrames (Veri Çerçeveleri)

In [91]:
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [92]:
lang = ['Java', 'Python', 'C', 'C++']
df = pd.DataFrame(lang)
df

0
0    Java
1  Python
2       C
3     C++

In [93]:
rating = [1,2,3,4]
df[1] = rating
df

0  1
0    Java  1
1  Python  2
2       C  3
3     C++  4

In [94]:
df.columns = ['Language', 'Rating']

In [95]:
df

Language  Rating
0     Java       1
1   Python       2
2        C       3
3      C++       4

In [96]:
#DF from dictionary

In [27]:
data = [{'a' : 1, 'b' : 2}, {'a' : 5, 'b' : 10, 'c' : 20}]

df2 = pd.DataFrame(data)
df2

a   b     c
0  1   2   NaN
1  5  10  20.0

In [28]:
df3 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b'])
df3

a   b
row1  1   2
row2  5  10

In [29]:
df4 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c'])
df4

a   b     c
row1  1   2   NaN
row2  5  10  20.0

In [30]:
df5 = pd.DataFrame(data, index = ['row1', 'row2'], columns = ['a', 'b', 'c', 'd'])
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [31]:
mydict = {'A' : pd.Series([1,2,3], index = ['a', 'b', 'c']),
          'B' : pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])
         }

df1 = pd.DataFrame(mydict)
df1

A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [11]:
p1 = int(input("1. Anketin Sonucu : "))
p2 = int(input("2. Anketin Sonucu : "))
data = [{'a' : 1, 'b' : 2, 'c' : p1}, {'a' : 5, 'b' : 10, 'c' : p2}]
points = pd.DataFrame(data)
points

1. Anketin Sonucu : 90
2. Anketin Sonucu : 100


a   b    c
0  1   2   90
1  5  10  100

In [12]:
#Rastgele Sayılar ve Date İndeksleri kullanarak DF oluşturma

In [15]:
dates = pd.date_range(start = '2023-09-01', end = '2023-09-07')
dates

DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04',
               '2023-09-05', '2023-09-06', '2023-09-07'],
              dtype='datetime64[ns]', freq='D')

In [16]:
dates = pd.date_range('today', periods = 7)
dates

DatetimeIndex(['2023-09-05 22:11:20.484089', '2023-09-06 22:11:20.484089',
               '2023-09-07 22:11:20.484089', '2023-09-08 22:11:20.484089',
               '2023-09-09 22:11:20.484089', '2023-09-10 22:11:20.484089',
               '2023-09-11 22:11:20.484089'],
              dtype='datetime64[ns]', freq='D')

In [17]:
dates = pd.date_range(start = '2023-09-01', periods = 7)
dates

DatetimeIndex(['2023-09-01', '2023-09-02', '2023-09-03', '2023-09-04',
               '2023-09-05', '2023-09-06', '2023-09-07'],
              dtype='datetime64[ns]', freq='D')

In [18]:
M = np.random.random((7,7))
M

array([[0.04200319, 0.43679952, 0.52972066, 0.59149822, 0.09083386,
        0.71276142, 0.34375318],
       [0.27819538, 0.7219132 , 0.7818754 , 0.21733095, 0.29506415,
        0.75565294, 0.42037966],
       [0.82920727, 0.50578267, 0.96339137, 0.7939454 , 0.5573892 ,
        0.94817005, 0.42435557],
       [0.72199285, 0.10199634, 0.10903415, 0.54259578, 0.41268975,
        0.02332283, 0.63787629],
       [0.9593854 , 0.59661021, 0.38669384, 0.77911925, 0.59972017,
        0.36387994, 0.60228732],
       [0.94831157, 0.02148282, 0.5284375 , 0.85213393, 0.66891411,
        0.35619183, 0.90401259],
       [0.7158419 , 0.19279709, 0.30219117, 0.86335886, 0.27400131,
        0.44763365, 0.89704235]])

In [19]:
dframe = pd.DataFrame(M, index = dates)
dframe

0         1         2         3         4         5  \
2023-09-01  0.042003  0.436800  0.529721  0.591498  0.090834  0.712761   
2023-09-02  0.278195  0.721913  0.781875  0.217331  0.295064  0.755653   
2023-09-03  0.829207  0.505783  0.963391  0.793945  0.557389  0.948170   
2023-09-04  0.721993  0.101996  0.109034  0.542596  0.412690  0.023323   
2023-09-05  0.959385  0.596610  0.386694  0.779119  0.599720  0.363880   
2023-09-06  0.948312  0.021483  0.528438  0.852134  0.668914  0.356192   
2023-09-07  0.715842  0.192797  0.302191  0.863359  0.274001  0.447634   

                   6  
2023-09-01  0.343753  
2023-09-02  0.420380  
2023-09-03  0.424356  
2023-09-04  0.637876  
2023-09-05  0.602287  
2023-09-06  0.904013  
2023-09-07  0.897042

In [20]:
dframe.columns = ['C1', 'C2', 'C3', 'C4', 'C5', 'C6', 'C7']
dframe

C1        C2        C3        C4        C5        C6  \
2023-09-01  0.042003  0.436800  0.529721  0.591498  0.090834  0.712761   
2023-09-02  0.278195  0.721913  0.781875  0.217331  0.295064  0.755653   
2023-09-03  0.829207  0.505783  0.963391  0.793945  0.557389  0.948170   
2023-09-04  0.721993  0.101996  0.109034  0.542596  0.412690  0.023323   
2023-09-05  0.959385  0.596610  0.386694  0.779119  0.599720  0.363880   
2023-09-06  0.948312  0.021483  0.528438  0.852134  0.668914  0.356192   
2023-09-07  0.715842  0.192797  0.302191  0.863359  0.274001  0.447634   

                  C7  
2023-09-01  0.343753  
2023-09-02  0.420380  
2023-09-03  0.424356  
2023-09-04  0.637876  
2023-09-05  0.602287  
2023-09-06  0.904013  
2023-09-07  0.897042

In [21]:
dframe.dtypes

C1    float64
C2    float64
C3    float64
C4    float64
C5    float64
C6    float64
C7    float64
dtype: object

In [22]:
dframe.sort_values(by = 'C1') #ascending

C1        C2        C3        C4        C5        C6  \
2023-09-01  0.042003  0.436800  0.529721  0.591498  0.090834  0.712761   
2023-09-02  0.278195  0.721913  0.781875  0.217331  0.295064  0.755653   
2023-09-07  0.715842  0.192797  0.302191  0.863359  0.274001  0.447634   
2023-09-04  0.721993  0.101996  0.109034  0.542596  0.412690  0.023323   
2023-09-03  0.829207  0.505783  0.963391  0.793945  0.557389  0.948170   
2023-09-06  0.948312  0.021483  0.528438  0.852134  0.668914  0.356192   
2023-09-05  0.959385  0.596610  0.386694  0.779119  0.599720  0.363880   

                  C7  
2023-09-01  0.343753  
2023-09-02  0.420380  
2023-09-07  0.897042  
2023-09-04  0.637876  
2023-09-03  0.424356  
2023-09-06  0.904013  
2023-09-05  0.602287

In [24]:
dframe.sort_values(by = 'C1', ascending = False) #descending

C1        C2        C3        C4        C5        C6  \
2023-09-05  0.959385  0.596610  0.386694  0.779119  0.599720  0.363880   
2023-09-06  0.948312  0.021483  0.528438  0.852134  0.668914  0.356192   
2023-09-03  0.829207  0.505783  0.963391  0.793945  0.557389  0.948170   
2023-09-04  0.721993  0.101996  0.109034  0.542596  0.412690  0.023323   
2023-09-07  0.715842  0.192797  0.302191  0.863359  0.274001  0.447634   
2023-09-02  0.278195  0.721913  0.781875  0.217331  0.295064  0.755653   
2023-09-01  0.042003  0.436800  0.529721  0.591498  0.090834  0.712761   

                  C7  
2023-09-05  0.602287  
2023-09-06  0.904013  
2023-09-03  0.424356  
2023-09-04  0.637876  
2023-09-07  0.897042  
2023-09-02  0.420380  
2023-09-01  0.343753

In [25]:
#Silme 

In [32]:
df1

A  B
a  1.0  1
b  2.0  2
c  3.0  3
d  NaN  4

In [33]:
del df1['B']

In [34]:
df1

A
a  1.0
b  2.0
c  3.0
d  NaN

In [35]:
df5

a   b     c   d
row1  1   2   NaN NaN
row2  5  10  20.0 NaN

In [36]:
df5.pop('c')

row1     NaN
row2    20.0
Name: c, dtype: float64

In [37]:
df5

a   b   d
row1  1   2 NaN
row2  5  10 NaN

In [39]:
mydict = {'A' : pd.Series([1,2,3,11], index = ['a', 'b', 'c', 'd']),
          'B' : pd.Series([1,2,3,4], index = ['a', 'b', 'c', 'd'])
         }

df12 = pd.DataFrame(mydict)
df12

A  B
a   1  1
b   2  2
c   3  3
d  11  4

In [40]:
df12.drop(['A'], axis = 1, inplace = True)
df12

B
a  1
b  2
c  3
d  4

In [41]:
#Satır Silme

In [42]:
col1 = np.linspace(10, 100, 30)
col2 = np.random.randint(10, 100, 30)
df10 = pd.DataFrame({'C1' : col1, 'C2' : col2})
df10

C1  C2
0    10.000000  69
1    13.103448  97
2    16.206897  80
3    19.310345  47
4    22.413793  21
5    25.517241  75
6    28.620690  41
7    31.724138  71
8    34.827586  58
9    37.931034  97
10   41.034483  99
11   44.137931  24
12   47.241379  67
13   50.344828  93
14   53.448276  55
15   56.551724  63
16   59.655172  37
17   62.758621  65
18   65.862069  63
19   68.965517  58
20   72.068966  59
21   75.172414  23
22   78.275862  64
23   81.379310  41
24   84.482759  70
25   87.586207  88
26   90.689655  75
27   93.793103  48
28   96.896552  25
29  100.000000  30

In [43]:
df10 = df10.drop([17,18,19], axis = 0)
df10

C1  C2
0    10.000000  69
1    13.103448  97
2    16.206897  80
3    19.310345  47
4    22.413793  21
5    25.517241  75
6    28.620690  41
7    31.724138  71
8    34.827586  58
9    37.931034  97
10   41.034483  99
11   44.137931  24
12   47.241379  67
13   50.344828  93
14   53.448276  55
15   56.551724  63
16   59.655172  37
20   72.068966  59
21   75.172414  23
22   78.275862  64
23   81.379310  41
24   84.482759  70
25   87.586207  88
26   90.689655  75
27   93.793103  48
28   96.896552  25
29  100.000000  30

In [44]:
df10.drop([16], axis = 0, inplace = True)
df10

C1  C2
0    10.000000  69
1    13.103448  97
2    16.206897  80
3    19.310345  47
4    22.413793  21
5    25.517241  75
6    28.620690  41
7    31.724138  71
8    34.827586  58
9    37.931034  97
10   41.034483  99
11   44.137931  24
12   47.241379  67
13   50.344828  93
14   53.448276  55
15   56.551724  63
20   72.068966  59
21   75.172414  23
22   78.275862  64
23   81.379310  41
24   84.482759  70
25   87.586207  88
26   90.689655  75
27   93.793103  48
28   96.896552  25
29  100.000000  30

In [45]:
df10.drop(df10.index[5], inplace = True)
df10

C1  C2
0    10.000000  69
1    13.103448  97
2    16.206897  80
3    19.310345  47
4    22.413793  21
6    28.620690  41
7    31.724138  71
8    34.827586  58
9    37.931034  97
10   41.034483  99
11   44.137931  24
12   47.241379  67
13   50.344828  93
14   53.448276  55
15   56.551724  63
20   72.068966  59
21   75.172414  23
22   78.275862  64
23   81.379310  41
24   84.482759  70
25   87.586207  88
26   90.689655  75
27   93.793103  48
28   96.896552  25
29  100.000000  30

In [46]:
df10 = df10.iloc[3:]
df10

C1  C2
3    19.310345  47
4    22.413793  21
6    28.620690  41
7    31.724138  71
8    34.827586  58
9    37.931034  97
10   41.034483  99
11   44.137931  24
12   47.241379  67
13   50.344828  93
14   53.448276  55
15   56.551724  63
20   72.068966  59
21   75.172414  23
22   78.275862  64
23   81.379310  41
24   84.482759  70
25   87.586207  88
26   90.689655  75
27   93.793103  48
28   96.896552  25
29  100.000000  30

In [47]:
df10 = df10.iloc[:-4,]

In [48]:
df10

C1  C2
3   19.310345  47
4   22.413793  21
6   28.620690  41
7   31.724138  71
8   34.827586  58
9   37.931034  97
10  41.034483  99
11  44.137931  24
12  47.241379  67
13  50.344828  93
14  53.448276  55
15  56.551724  63
20  72.068966  59
21  75.172414  23
22  78.275862  64
23  81.379310  41
24  84.482759  70
25  87.586207  88

In [49]:
df10.index[df10['C2'] == 41].tolist()

[6, 23]

In [50]:
df10.drop(df10.index[df10['C2'] == 41].tolist(), axis = 0, inplace = True)
df10

C1  C2
3   19.310345  47
4   22.413793  21
7   31.724138  71
8   34.827586  58
9   37.931034  97
10  41.034483  99
11  44.137931  24
12  47.241379  67
13  50.344828  93
14  53.448276  55
15  56.551724  63
20  72.068966  59
21  75.172414  23
22  78.275862  64
24  84.482759  70
25  87.586207  88

In [ ]:
#Silmede AND kullanımı