In [1]:
f = open("2908test.txt", "w")
print(f)

<_io.TextIOWrapper name='2908test.txt' mode='w' encoding='cp1254'>


In [2]:
f.write("Now is the time")
f.write(" to close the file")

f.close()

In [3]:
f = open("2908test.txt", "r")
text = f.read()
print(text)

Now is the time to close the file


In [4]:
f = open("2908test.txt", "r")
print(f.read(5))

Now i


In [5]:
print(f.read(1000006))

s the time to close the file


In [6]:
fo = open("2908foo.txt", "w")
fo.write("Python is a great language.\nYeah its great!!\n")

fo = open("2908foo.txt", "r+")
mystr1 = fo.read(17)
print("Our string is : ", mystr1)

Our string is :  Python is a great


In [7]:
position = fo.tell()
print("Current file position : ", position)

Current file position :  17


In [8]:
position = fo.seek(0, 0)
mystr1 = fo.read(17)
print("Again our string is : ", mystr1)

fo.close()

Again our string is :  Python is a great


In [9]:
#try-except-else-finally

In [10]:
try:
    fh = open("2908testfile", "r")
    fh.write("This is my test file for exception handling")
    
except IOError:
    print("Error : cannot find file or read data")
    
else:
    print("Content is written to the file successfully")

Error : cannot find file or read data


In [11]:
try:
    fh = open("2908testfile", "w")
    fh.write("This is my test file for exception handling")
    
finally:
    print("Content is written to the file successfully")

Content is written to the file successfully


In [12]:
#Sözlükler (Dictionaries)

In [14]:
mydict = {'Name' : 'Bilge', 'Age' : 1, 'Class' : 'First'}
print(mydict['Name'])
print(mydict['Age'])

Bilge
1


In [15]:
mydict = {'Name' : 'Bilge', 'Age' : 1, 'Class' : 'First'}
mydict['Age'] = 8
mydict['School'] = 'Primary School'
print(mydict['Age'])
print(mydict['School'])

8
Primary School


In [16]:
mydict = {'Name' : 'Bilge', 'Age' : 1, 'Name' : 'Poyraz'}
mydict['Name']

'Poyraz'

In [17]:
#silme
mydict = {'Name' : 'Bilge', 'Age' : 1, 'Class' : 'First'}
del mydict['Name']
mydict.clear()
del mydict

In [18]:
print(mydict['Age'])
print(mydict['School'])

NameError: name 'mydict' is not defined

In [19]:
#get/items metotları

In [20]:
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222'}
value = phonebook.get('Katie')
print(value)

555-2222


In [23]:
phonebook = {'Chris' : '555-1111', 'Katie' : '555-2222', 'Joe' : '555-3333'}
for key, value in phonebook.items():
    print(key, ':', value)

Chris : 555-1111
Katie : 555-2222
Joe : 555-3333


In [24]:
import numpy as np
import warnings
warnings.filterwarnings('ignore')

In [25]:
list1 = [10,20,30,40,50,60]
list1

[10, 20, 30, 40, 50, 60]

In [26]:
type(list1)

list

In [27]:
arr1 = np.array(list1)
arr1

array([10, 20, 30, 40, 50, 60])

In [28]:
arr1.data

In [29]:
type(arr1)

numpy.ndarray

In [30]:
arr1.dtype

dtype('int32')

In [31]:
arr1.nbytes

24

In [32]:
arr1.astype(float)

array([10., 20., 30., 40., 50., 60.])

In [33]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [34]:
np.arange(0, 100, 10)

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [35]:
np.arange(100, 10, -10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [36]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [37]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [38]:
np.repeat(10, 5)

array([10, 10, 10, 10, 10])

In [39]:
a = np.array([10, 20, 30])
np.repeat(a, 3)

array([10, 10, 10, 20, 20, 20, 30, 30, 30])

In [40]:
np.full(5, 10)

array([10, 10, 10, 10, 10])

In [41]:
ar1 = np.arange(1, 20)
ar1[ar1 %2 == 1]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [44]:
ar1 = np.arange(0, 22)
ar1[ar1 %2 == 0]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [45]:
np.linspace(10, 20, 4)

array([10.        , 13.33333333, 16.66666667, 20.        ])

In [46]:
np.linspace(10, 20, 11)

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19., 20.])

In [47]:
np.random.random(4)

array([0.54430635, 0.15513105, 0.70788101, 0.59492538])

In [48]:
np.random.randint(0, 500, 5)

array([ 24, 315,  67, 172, 459])

In [55]:
np.random.randint(0, 500, 10)

array([ 96, 208,  68, 305, 311, 451,   2, 340,  39, 322])

In [52]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [53]:
np.random.seed(123)
np.random.randint(0, 100, 10)

array([66, 92, 98, 17, 83, 57, 86, 97, 96, 47])

In [56]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [57]:
np.random.seed(101)
np.random.randint(0, 100, 10)

array([95, 11, 81, 70, 63, 87, 75,  9, 77, 40])

In [58]:
f1 = np.random.uniform(5, 10, size = (10))
f1

array([6.5348311 , 9.4680654 , 8.60771931, 5.94969477, 7.77113796,
       6.76065977, 5.90946201, 8.92800881, 9.82741611, 6.16176831])

In [59]:
np.floor(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [60]:
np.trunc(f1)

array([6., 9., 8., 5., 7., 6., 5., 8., 9., 6.])

In [61]:
f1.astype(int)

array([6, 9, 8, 5, 7, 6, 5, 8, 9, 6])

In [62]:
b2 = np.random.randn(10)
b2

array([ 0.18869531, -0.75887206, -0.93323722,  0.95505651,  0.19079432,
        1.97875732,  2.60596728,  0.68350889,  0.30266545,  1.69372293])

In [63]:
arr1

array([10, 20, 30, 40, 50, 60])

In [64]:
for index, value in np.ndenumerate(arr1):
    print(index, value)

(0,) 10
(1,) 20
(2,) 30
(3,) 40
(4,) 50
(5,) 60


In [65]:
#Diziler üzerinde yapılan operasyonlar

In [66]:
arr2 = np.arange(1, 20)
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [67]:
arr2.sum()

190

In [68]:
np.cumsum(arr2)

array([  1,   3,   6,  10,  15,  21,  28,  36,  45,  55,  66,  78,  91,
       105, 120, 136, 153, 171, 190], dtype=int32)

In [69]:
#min(), max(), argmin(), argmax(), mean(), median(), var()

In [70]:
np.std(arr2)

5.477225575051661

In [71]:
#2-Boyutlu Diziler üzerindeki operasyonlar

In [72]:
A = np.array([[1,2,3,0], [5,6,7,22], [10, 11, 1, 13], [14,15,16,3]])
A

array([[ 1,  2,  3,  0],
       [ 5,  6,  7, 22],
       [10, 11,  1, 13],
       [14, 15, 16,  3]])

In [73]:
A.sum()

129

In [74]:
#max(), min(), mean(), median(), var(), std()

In [75]:
np.amin(A, axis = 0)

array([1, 2, 1, 0])

In [76]:
np.amin(A, axis = 1)

array([0, 5, 1, 3])

In [77]:
for index, value in np.ndenumerate(A):
    print(index, value)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 0
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 22
(2, 0) 10
(2, 1) 11
(2, 2) 1
(2, 3) 13
(3, 0) 14
(3, 1) 15
(3, 2) 16
(3, 3) 3


In [78]:
a = np.array([7,5,3,9,0,2])
a

array([7, 5, 3, 9, 0, 2])

In [79]:
a[0]

7

In [80]:
a[1:]

array([5, 3, 9, 0, 2])

In [81]:
a[1:4]

array([5, 3, 9])

In [82]:
a[-1]

2

In [83]:
a[-3]

9

In [84]:
a[-6]

7

In [85]:
a[-3:-1]

array([9, 0])

In [ ]:
#Dizideki elemanları değiştirme (replacing)